/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayIndexRouteImport } from './routes/today.index'
import { Route as PlanIndexRouteImport } from './routes/plan.index'
import { Route as TodayDateRouteImport } from './routes/today.$date'
import { Route as PlanMonthRouteImport } from './routes/plan.$month'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodayRoute,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanRoute,
} as any)
const TodayDateRoute = TodayDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => TodayRoute,
} as any)
const PlanMonthRoute = PlanMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => PlanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/plan/$month': typeof PlanMonthRoute
  '/today/$date': typeof TodayDateRoute
  '/plan/': typeof PlanIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plan/$month': typeof PlanMonthRoute
  '/today/$date': typeof TodayDateRoute
  '/plan': typeof PlanIndexRoute
  '/today': typeof TodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/plan/$month': typeof PlanMonthRoute
  '/today/$date': typeof TodayDateRoute
  '/plan/': typeof PlanIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plan'
    | '/today'
    | '/plan/$month'
    | '/today/$date'
    | '/plan/'
    | '/today/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/plan/$month' | '/today/$date' | '/plan' | '/today'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/plan'
    | '/today'
    | '/plan/$month'
    | '/today/$date'
    | '/plan/'
    | '/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRouteWithChildren
  TodayRoute: typeof TodayRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof TodayRoute
    }
    '/plan/': {
      id: '/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof PlanRoute
    }
    '/today/$date': {
      id: '/today/$date'
      path: '/$date'
      fullPath: '/today/$date'
      preLoaderRoute: typeof TodayDateRouteImport
      parentRoute: typeof TodayRoute
    }
    '/plan/$month': {
      id: '/plan/$month'
      path: '/$month'
      fullPath: '/plan/$month'
      preLoaderRoute: typeof PlanMonthRouteImport
      parentRoute: typeof PlanRoute
    }
  }
}

interface PlanRouteChildren {
  PlanMonthRoute: typeof PlanMonthRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanMonthRoute: PlanMonthRoute,
  PlanIndexRoute: PlanIndexRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

interface TodayRouteChildren {
  TodayDateRoute: typeof TodayDateRoute
  TodayIndexRoute: typeof TodayIndexRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayDateRoute: TodayDateRoute,
  TodayIndexRoute: TodayIndexRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRouteWithChildren,
  TodayRoute: TodayRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
